=== Qingchuan-Ma/https-github.com-Qingchuan-Ma-web_tech_summary/y2017g48/apache/htdocs/codefile/homework8/recipes.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="https://qingchuan-ma.github.io/blog" targetNamespace="https://qingchuan-ma.github.io/blog" elementFormDefault="qualified">

<xs:element name="Cookbook">
  <xs:complexType>
    <xs:element name="Recipe" maxOccurs="unbounded">
      <xs:complexType>

        <xs:element name="Index">
          <xs:simpleType>
            <xs:restriction base = "xs:decimal">
              <xs:minInclusive value = "1" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="Ingredientlist">
          <xs:complexType>
            <xs:element name="ingredient" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="name"
                              type="xs:string"
                              minOccurs = "1"
                              maxOccurs = "1"/>
                  <xs:element name="amount"
                              type="xs:integer"
                              minOccurs = "1"
                              maxOccurs = "1"/>
                  <xs:element name="unit"
                              type="xs:string"
                              minOccurs = "1"
                              maxOccurs = "1"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:complexType>
        </xs:element>


        <xs:element name="Procedure">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="first"
                          type="xs:string"
                          minOccurs = "1"
                          maxOccurs = "1"/>
              <xs:element name="second"
                          type="xs:string"
                          minOccurs = "1"
                          maxOccurs = "1"/>
              <xs:element name="third"
                          type="xs:string"
                          minOccurs = "1"
                          maxOccurs = "1"/>
              </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:complexType>
    </xs:element>

  </xs:complexType>
</xs:element>

</xs:schema>

=== Qingchuan-Ma/https-github.com-Qingchuan-Ma-web_tech_summary/y2017g48/apache/htdocs/codefile/homework8/recipes.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="recipes.xsl"?>

<Cookbook xmlns:xsi =  "http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation = "https://qingchuan-ma.github.io/blog recipes.xsd" >
<Recipe>
  <Index>1</Index>
  <Name>Rhubarb and Custard</Name>
  <Ingredientlist>
    <ingredient>
      <name>Milk</name>
      <amount>15</amount>
      <unit>ml</unit>
    </ingredient>
    <ingredient>
      <name>Rhubarb</name>
      <amount>700</amount>
      <unit>g</unit>
    </ingredient>
    <ingredient>
      <name>Custard Powder</name>
      <amount>8</amount>
      <unit>tbs</unit>
    </ingredient>
  </Ingredientlist>
  <Procedure>
    <first>Prepare ingredient</first>
    <second>Mix together and put in oven proof dish</second>
    <third>Heat in a moderate oven for 40 mins</third>
  </Procedure>
</Recipe>


<Recipe>
  <Index>2</Index>
  <Name>Ice Cream Sundae</Name>
  <Ingredients>
    <ingredient>
      <name>chocolate syrup</name>
      <amount>3</amount>
      <unit></unit>
    </ingredient>
    <ingredient>
      <name>cherry</name>
      <amount>1</amount>
      <unit></unit>
    </ingredient>
    <ingredient>
      <name>nuts</name>
      <amount>1</amount>
      <unit></unit>
    </ingredient>
  </Ingredients>
  <Procedure>
    <first>Using ice cream scoop, place vanilla ice cream into bowl.</first>
    <second>Drizzle chocolate syrup or chocolate fudge over the ice cream.</second>
    <third>Sprinkle nuts over the mound of chocolate and ice cream,and put cherry on top of mound</third>
  </Procedure>
</Recipe>


</Cookbook>
